### PR TITLE
Instances json "API"

### PR DESCRIPTION
**Pull request by alopix**
I’ve added a minor tweak to the generator script which will also write a `instances.json` file in order for e.g. apps to provide the same list of instances as the website.
I hope that is okey. Otherwise I’ll host that myself, but I thought it would be nice to have on the "main" join website.

### CODE REVIEW

**Comment by alopix** [comment]
Would it make sense to wrap the array in an object that contains some metadata, like "last generated" or will your deployment send that as a header?

**Comment by alopix** [comment]
I just ran the linter and it does not seem to get installed by default (at least get an error). After manually installing, running `black` works though—might be something to look into.

**Comment by mouse-reeve** [comment]
I believe black is in the requirements.txt file, but there isn't much documented on editing this site at all. Thank you for diving into the codebase anyway!

**Comment by mouse-reeve** [comment]
Wow I forgot about this! I'm going to merge it into another branch and change it a bit to filter what gets included in the json file, because some of the data is weird out of context

**Comment by alopix** [comment]
Thanks. I actually completely forgot about thus one this one as well. I made my own repo which is updated every Sunday with the current instance infos—based off of the registered instances over here: https://github.com/MeecoLabs/join-bookwyrm-instances/

**Pull request merged**
